Repository thoth-station/investigator, pull requests merged in 2020-08, with the labels that each got.

#132 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/L

#133 Automatic update of dependency thoth-messaging from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: approved, bot, size/L

#134 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#135 Automatic update of dependency pytest from 5.4.3 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/L

#136 Automatic update of dependency hypothesis from 5.23.2 to 5.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#142 use sorting method from thoth-python
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/XS

#144 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/S

#146 Automatic update of dependency hypothesis from 5.24.0 to 5.24.2
  Pipfile.lock
Labels: approved, bot, size/S

#159 Add methods to handle Unrevsolved Package Message
  README.md
  consumer.py
  thoth/investigator/common.py
  thoth/investigator/investigate_unresolved_package.py
  thoth/investigator/investigate_unrevsolved_package.py
Labels: approved, size/L

#161 Automatic update of dependency thoth-storages from 0.25.4 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/S

#164 Release of version 0.4.2
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#162 Automatic update of dependency hypothesis from 5.27.0 to 5.28.0
  Pipfile.lock
Labels: approved, bot, size/S

#163 Automatic update of dependency pytest-mypy from 0.6.2 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/XS

#172 Automatic update of dependency thoth-messaging from 0.6.5 to 0.6.7
  Pipfile.lock
Labels: approved, bot, size/M

#173 Automatic update of dependency hypothesis from 5.28.0 to 5.29.1
  Pipfile.lock
Labels: approved, bot, size/M

#171 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/S

#174 Automatic update of dependency hypothesis from 5.29.1 to 5.30.0
  Pipfile.lock
Labels: approved, bot, size/M
