Repository thoth-station/investigator, pull requests merged in 2020-09, with the labels that each got.

#177 Automatic update of dependency thoth-messaging from 0.6.7 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/M

#176 Automatic update of dependency thoth-common from 0.17.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/XS

#175 Move consumer logic
  Pipfile
  Pipfile.lock
  README.md
  consumer.py
  investigator/investigator/__init__.py
  investigator/investigator/advise_justification/__init__.py
  investigator/investigator/advise_justification/investigate_advise_justification.py
  investigator/investigator/advise_justification/metrics_advise_justification.py
  investigator/investigator/common.py
  investigator/investigator/hash_mismatch/__init__.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/hash_mismatch/metrics_hash_mismatch.py
  investigator/investigator/metrics.py
  investigator/investigator/missing_package/__init__.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/missing_package/metrics_missing_package.py
  investigator/investigator/missing_version/__init__.py
  investigator/investigator/missing_version/investigate_missing_version.py
  investigator/investigator/missing_version/metrics_missing_version.py
  investigator/investigator/solved_package/__init__.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/solved_package/metrics_solved_package.py
  investigator/investigator/unresolved_package/__init__.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unresolved_package/metrics_unresolved_package.py
  investigator/investigator/unrevsolved_package/__init__.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
  investigator/investigator/unrevsolved_package/metrics_unrevsolved_package.py
Labels: approved, size/XXL

#183 Automatic update of dependency hypothesis from 5.30.0 to 5.33.2
  Pipfile.lock
Labels: approved, bot, size/L

#181 Automatic update of dependency thoth-common from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/L

#184 Release of version 0.4.3
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/M

#185 add component and version to message
  Pipfile.lock
  producer.py
Labels: approved, size/M

#188 Automatic update of dependency thoth-common from 0.17.3 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/M

#189 Release of version 0.4.4
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#190 Automatic update of dependency thoth-common from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/XS

#191 Automatic update of dependency thoth-storages from 0.25.6 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/XS

#193 Automatic update of dependency hypothesis from 5.33.2 to 5.35.0
  Pipfile.lock
Labels: approved, bot, size/S

#192 Add Investigate AdviserReRunMessage to Investigator
  consumer.py
  investigator/investigator/adviser_re_run/__init__.py
  investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
  investigator/investigator/adviser_re_run/metrics_adviser_re_run.py
  investigator/investigator/metrics.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
Labels: approved, size/L

#195 Release of version 0.4.5
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#196 Automatic update of dependency thoth-common from 0.18.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/XS

#202 Automatic update of dependency hypothesis from 5.35.0 to 5.35.2
  Pipfile.lock
Labels: approved, bot, size/L

#200 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/L

#198 Automatic update of dependency thoth-common from 0.18.2 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/L

#199 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/L

#207 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/M

#206 handle package released messages
  consumer.py
  investigator/investigator/common.py
  investigator/investigator/package_released/__init__.py
  investigator/investigator/package_released/investigate_package_released.py
  investigator/investigator/package_released/metrics_package_released.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
Labels: approved, size/L

#209 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot

#211 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot, size/XS

#216 Automatic update of dependency thoth-sourcemanagement from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: approved, bot, size/S

#213 Automatic update of dependency hypothesis from 5.35.2 to 5.35.3
  Pipfile.lock
Labels: approved, bot, size/XS

#210 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.2
  Pipfile.lock
Labels: approved, bot, size/XS

#212 Added logic to process SI Unanalyzed messages
  README.md
  consumer.py
  investigator/investigator/si_unanalyzed_package/__init__.py
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  investigator/investigator/si_unanalyzed_package/metrics_si_unanalyzed_package.py
Labels: approved, size/L

#218 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#220 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/S

#221 Remove SI scheduling from UnresolvedPackageMessage
  consumer.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
Labels: approved, size/M

#222 Automatic update of dependency thoth-messaging from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: approved, bot, size/XS

#214 add consumers for workflow triggers
  Pipfile
  Pipfile.lock
  consumer.py
  investigator/investigator/adviser_trigger/__init__.py
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
  investigator/investigator/adviser_trigger/metrics_adviser_trigger.py
  investigator/investigator/kebechet_trigger/__init__.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/kebechet_trigger/metrics_kebechet_trigger.py
  investigator/investigator/package_extract_trigger/__init__.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  investigator/investigator/package_extract_trigger/metrics_package_extract_trigger.py
  investigator/investigator/provenance_checker_trigger/__init__.py
  investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  investigator/investigator/provenance_checker_trigger/metrics_provenance_checker_trigger.py
  investigator/investigator/qebhwt_trigger/__init__.py
  investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  investigator/investigator/qebhwt_trigger/metrics_qebhwt_trigger.py
Labels: approved, size/XL

#224 Release of version 0.4.6
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#225 patch fix the variable reference for metrics
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
Labels: approved, size/S

#228 Release of version 0.4.7
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#230 Automatic update of dependency thoth-messaging from 0.7.3 to 0.7.6
  Pipfile.lock
Labels: approved, bot, size/L

#233 Update and refactor docs
  README.md
  investigator/investigator/advise_justification/README.md
  investigator/investigator/adviser_re_run/README.md
  investigator/investigator/adviser_trigger/README.md
  investigator/investigator/hash_mismatch/README.md
  investigator/investigator/kebechet_trigger/README.md
  investigator/investigator/missing_package/README.md
  investigator/investigator/missing_version/README.md
  investigator/investigator/package_extract_trigger/README.md
  investigator/investigator/package_released/README.md
  investigator/investigator/provenance_checker_trigger/README.md
  investigator/investigator/qebhwt_trigger/README.md
  investigator/investigator/si_unanalyzed_package/README.md
  investigator/investigator/solved_package/README.md
  investigator/investigator/unresolved_package/README.md
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/README.md
Labels: approved, size/L

#237 Adjust logging
  README.md
  investigator/investigator/common.py
Labels: approved, size/XS

#242 Automatic update of dependency hypothesis from 5.35.3 to 5.35.4
  Pipfile.lock
Labels: approved, bot, size/M

#241 Automatic update of dependency thoth-sourcemanagement from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: approved, bot, size/M

#240 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/S

#245 Adjust links in README
  README.md
  investigator/investigator/adviser_trigger/README.md
Labels: approved, size/S

#248 Release of version 0.4.8
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#251 Automatic update of dependency hypothesis from 5.35.4 to 5.36.0
  Pipfile.lock
Labels: approved, bot, size/L

#250 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#253 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/L

#258 Release of version 0.4.9
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#259 correct the investigate_unresolved_package import
  investigator/investigator/unresolved_package/__init__.py
  producer.py
Labels: approved, size/XS

#215 add decorator to submit workflow to wait for pending limit
  Pipfile.lock
  consumer.py
  investigator/investigator/advise_justification/investigate_advise_justification.py
  investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
  investigator/investigator/common.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  investigator/investigator/package_released/investigate_package_released.py
  investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
Labels: approved, size/L

#261 Release of version 0.4.10
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#263 Correct wrong message
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
Labels: approved, size/XS

#266 Automatic update of dependency hypothesis from 5.36.0 to 5.36.1
  Pipfile.lock
Labels: approved, bot, size/S

#267 Release of version 0.4.11
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#269 make func async
  investigator/investigator/missing_version/investigate_missing_version.py
Labels: approved, size/XS

#271 Release of version 0.4.12
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#273 add all env variables to README
  README.md
Labels: approved, size/XS

#277 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.7
  Pipfile.lock
Labels: approved, bot, size/M

#278 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#276 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.12
  Pipfile.lock
Labels: approved, bot, size/M

#279 Automatic update of dependency thoth-messaging from 0.7.7 to 0.7.8
  Pipfile.lock
Labels: approved, bot, size/S

#280 Automatic update of dependency thoth-storages from 0.25.12 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/XS

#282 Add images for Thoth Learning using Kafka
  README.md
  investigator/investigator/images/FailedAdviceAdviserReRun.jpg
  investigator/investigator/images/IncreaseThothKnowledge.jpg
Labels: approved, size/S

#285 Release of version 0.4.13
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#286 Describe User-API Investigator interaction
  README.md
  investigator/investigator/images/UserAPIKafkaProducer.jpg
Labels: approved, size/XS

#288 Remove parameter not existing in message in thoth-messaging
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
Labels: approved, size/XS

#290 Release of version 0.4.14
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#291 Add workflow namespace variables for quota limit check
  consumer.py
  investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
  investigator/investigator/common.py
  investigator/investigator/configuration.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  investigator/investigator/package_released/investigate_package_released.py
  investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
Labels: approved, size/L

#293 Release of version 0.5.0
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS
