Repository thoth-station/investigator, pull requests merged in 2020-07, with the labels that each got.

#51 Automatic update of dependency thoth-common from 0.13.13 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#54 Remove not required parameters
  thoth/unresolved_package_handler/unresolved_package_handler.py
Labels: approved, size/S

#52 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.2
  Pipfile.lock
Labels: approved, bot, size/XS

#56 Release of version 0.1.2
  CHANGELOG.md
  thoth/unresolved_package_handler/__init__.py
Labels: approved, bot, size/S

#53 Automatic update of dependency hypothesis from 5.18.3 to 5.19.0
  Pipfile.lock
Labels: approved, bot, size/XS

#57 Automatic update of dependency thoth-storages from 0.24.2 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/S

#61 Modify code and update README after renaming the component
  Pipfile.lock
  README.md
  consumer.py
  producer.py
  thoth/investigator/__init__.py
  thoth/investigator/investigate_unresolved_package.py
Labels: size/L

#48 using pre-commit now, removed coala config
  .coafile
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  .zuul.yaml
  consumer.py
  producer.py
  tests/adviser-04ab56d6.json
  tests/test_unresolved_package_handler.py
  thoth/investigator/investigate_unresolved_package.py
Labels: size/L

#65 Release of version 0.2.0
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/S

#66 Remove templates
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/unresolved-package-handler-consumer-template.yaml
  producer.py
  thoth/investigator/__init__.py
  thoth/investigator/investigate_unresolved_package.py
  workflows/templates/unresolved-package-handler-template.yaml
Labels: approved, size/L

#67 minor missing piece
  consumer.py
Labels: approved, size/XS

#69 Release of version 0.2.1
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#71 Correct parameter from Kafka message
  thoth/investigator/investigate_unresolved_package.py
Labels: size/XS

#73 Release of version 0.2.2
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#75 Make producer more asynchronous by creating all futures before awaiting
  producer.py
Labels: approved, size/S

#77 Automatic update of dependency hypothesis from 5.19.0 to 5.19.2
  Pipfile.lock
Labels: approved, bot, size/M

#74 Add a few persistent metrics
  consumer.py
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/S

#80 Automatic update of dependency hypothesis from 5.19.2 to 5.19.3
  Pipfile.lock
Labels: approved, bot, size/S

#82 Release of version 0.2.3
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#76 a little more roubust app.sh
  app.sh
Labels: approved, size/M

#84 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/M

#85 Automatic update of dependency pytest-timeout from 1.4.1 to 1.4.2
  Pipfile.lock
Labels: approved, bot, size/M

#86 Release of version 0.2.4
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#88 point to the right context path
  .aicoe-ci.yaml
Labels: approved, size/XS

#90 Add Missing connection to database
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/S

#93 Release of version 0.2.5
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#94 Add more logging
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/M

#96 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/S

#97 Automatic update of dependency hypothesis from 5.19.3 to 5.20.0
  Pipfile.lock
Labels: approved, bot, size/S

#98 Release of version 0.2.6
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#100 Automatic update of dependency hypothesis from 5.20.0 to 5.20.1
  Pipfile.lock
Labels: approved, bot, size/XS

#102 Automatic update of dependency hypothesis from 5.20.1 to 5.20.2
  Pipfile.lock
Labels: approved, bot, size/M

#103 Schedule workflows
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/L

#105 Automatic update of dependency hypothesis from 5.20.2 to 5.20.3
  Pipfile.lock
Labels: approved, bot, size/S

#108 Feature/metrics
  Pipfile
  Pipfile.lock
  consumer.py
  thoth/investigator/__init__.py
  thoth/investigator/investigate_unresolved_package.py
  thoth/investigator/metrics.py
Labels: approved, size/L

#110 Release of version 0.2.7
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#114 Automatic update of dependency thoth-messaging from 0.3.7 to 0.5.0
  Pipfile.lock
Labels: approved, bot, size/S

#118 Automatic update of dependency hypothesis from 5.20.3 to 5.21.0
  Pipfile.lock
Labels: approved, bot, size/S

#117 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/S

#116 Add tests
  tests/__init__.py
  tests/base_test.py
  tests/data/adviser-04ab56d6.json
  tests/investigate_unresolved_package_test.py
Labels: approved, size/XXL

#120 Update README
  README.md
Labels: approved, size/S

#122 Release of version 0.3.0
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/S

#123 Automatic update of dependency thoth-messaging from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: approved, bot, size/S

#124 Consider all versions explicitly and loop backward from latest
  producer.py
  thoth/investigator/investigate_unresolved_package.py
Labels: approved, size/S

#127 Automatic update of dependency thoth-messaging from 0.6.0 to 0.6.2
  Pipfile.lock
Labels: approved, bot, size/L

#129 Release of version 0.4.0
  CHANGELOG.md
  thoth/investigator/__init__.py
Labels: approved, bot, size/XS

#128 Automatic update of dependency hypothesis from 5.21.0 to 5.23.2
  Pipfile.lock
Labels: approved, bot, size/L

#131 Automatic update of dependency hypothesis from 5.21.0 to 5.23.2
  Pipfile.lock
Labels: approved, bot, size/S
