Repository thoth-station/investigator, pull requests merged in 2020-06, with the labels that each got.

#29 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#32 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: approved, bot

#33 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot

#35 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot

#36 Automatic update of dependency pytest-timeout from 1.3.4 to 1.4.1
  Pipfile.lock
Labels: approved, bot

#34 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot

#37 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot

#39 Automatic update of dependency hypothesis from 5.16.0 to 5.18.1
  Pipfile.lock
Labels: approved, bot

#40 Automatic update of dependency pytest-cov from 2.9.0 to 2.10.0
  Pipfile.lock
Labels: approved, bot

#42 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot

#45 Release of version 0.1.1
  CHANGELOG.md
  thoth/unresolved_package_handler/__init__.py
Labels: approved, bot

#47 Setuptools setup is required while build process
  setup.py
Labels: approved

#49 Automatic update of dependency hypothesis from 5.18.1 to 5.18.3
  Pipfile.lock
Labels: approved, bot, size/L
