Repository thoth-station/investigator, pull requests merged in 2020-10, with the labels that each got.

#295 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/M

#296 Automatic update of dependency thoth-messaging from 0.7.8 to 0.7.9
  Pipfile.lock
Labels: approved, bot, size/M

#281 Consume new message UpdateProvidesSourceDistroMessage
  Pipfile.lock
  consumer.py
  investigator/investigator/update_provide_source_distro/README.md
  investigator/investigator/update_provide_source_distro/__init__.py
  investigator/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
  investigator/investigator/update_provide_source_distro/metrics_update_provide_source_distro.py
Labels: approved, size/L

#298 Release of version 0.5.1
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#302 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/L

#303 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/L

#304 Automatic update of dependency hypothesis from 5.36.1 to 5.37.0
  Pipfile.lock
Labels: approved, bot, size/L

#275 use async prometheus
  Pipfile
  Pipfile.lock
  consumer.py
  investigator/investigator/advise_justification/investigate_advise_justification.py
  investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/missing_version/investigate_missing_version.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  investigator/investigator/package_released/investigate_package_released.py
  investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
Labels: approved, size/M

#307 Release of version 0.5.2
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#308 Add missing metrics
  investigator/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
Labels: approved, size/XS

#299 Update readme si
  README.md
  investigator/investigator/images/SIAnalysisOverview.png
  investigator/investigator/images/UpdateProvidesSourceDistro.jpg
Labels: approved, size/S

#310 Release of version 0.5.3
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#313 Add metrics to see what workflows are scheduled
  investigator/investigator/common.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/missing_version/investigate_missing_version.py
Labels: approved, size/M

#316 Automatic update of dependency thoth-messaging from 0.7.10 to 0.7.11
  Pipfile.lock
Labels: approved, bot, size/S

#320 Release of version 0.5.4
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#322 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/S

#323 Automatic update of dependency hypothesis from 5.37.0 to 5.37.1
  Pipfile.lock
Labels: approved, bot, size/S

#325 Release of version 0.5.5
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/XS

#327 Automatic update of dependency thoth-messaging from 0.7.11 to 0.7.12
  Pipfile.lock
Labels: approved, bot, size/M

#328 Automatic update of dependency mypy from 0.782 to 0.790
  Pipfile.lock
Labels: approved, bot, size/M

#329 Remove producer from investigator
  README.md
  app.sh
  investigator/investigator/common.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/unresolved_package/__init__.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  producer.py
Labels: approved, size/L

#331 Automatic update of dependency thoth-messaging from 0.7.12 to 0.7.13
  Pipfile.lock
Labels: approved, bot, size/L

#332 Automatic update of dependency hypothesis from 5.37.1 to 5.37.3
  Pipfile.lock
Labels: approved, bot, size/L

#330 Add docs for Thoth investigator
  README.md
  README.rst
  docs/source/_templates/layout.html
  docs/source/conf.py
  docs/source/index.rst
  investigator/investigator/images/FailedAdviceAdviserReRun.jpg
  investigator/investigator/images/IncreaseThothKnowledge.jpg
Labels: approved, size/XL

#338 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/S

#340 Automatic update of dependency thoth-messaging from 0.7.13 to 0.8.0
  Pipfile.lock
Labels: approved, bot, size/XS

#341 Automatic update of dependency hypothesis from 5.37.3 to 5.37.4
  Pipfile.lock
Labels: approved, bot, size/XS

#342 Add kebechet run url
  .gitignore
  README.rst
  consumer.py
  investigator/investigator/kebechet_run_url_trigger/README.md
  investigator/investigator/kebechet_run_url_trigger/__init__.py
  investigator/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  investigator/investigator/kebechet_run_url_trigger/metrics_kebechet_run_url_trigger.py
Labels: approved, size/L

#344 Confluent rework
  Pipfile
  Pipfile.lock
  README.rst
  app.sh
  consumer.py
  investigator/investigator/advise_justification/investigate_advise_justification.py
  investigator/investigator/adviser_re_run/investigate_adviser_re_run.py
  investigator/investigator/adviser_trigger/investigate_adviser_trigger.py
  investigator/investigator/common.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  investigator/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/missing_version/investigate_missing_version.py
  investigator/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  investigator/investigator/package_released/investigate_package_released.py
  investigator/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  investigator/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  investigator/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  investigator/investigator/solved_package/investigate_solved_package.py
  investigator/investigator/unresolved_package/investigate_unresolved_package.py
  investigator/investigator/unrevsolved_package/investigate_unrevsolved_package.py
  investigator/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
Labels: approved, size/XL

#345 Correct link
  README.rst
Labels: approved, size/XS

#349 add KPostOffice to list of maintainers
  .thoth.yaml
Labels: approved, hacktoberfest-accepted, size/XS

#347 Automatic update of dependency hypothesis from 5.37.4 to 5.38.0
  Pipfile.lock
Labels: approved, bot, size/L

#353 Automatic update of dependency thoth-messaging from 0.8.0 to 0.8.2
  Pipfile.lock
Labels: approved, bot, size/L

#354 Automatic update of dependency hypothesis from 5.38.0 to 5.38.1
  Pipfile.lock
Labels: approved, bot, size/L

#360 Release of version 0.6.0
  CHANGELOG.md
  investigator/investigator/__init__.py
Labels: approved, bot, size/S

#357 Added kebechet administrator triggers to message investigators
  README.rst
  consumer.py
  investigator/investigator/common.py
  investigator/investigator/configuration.py
  investigator/investigator/cve_provided/README.md
  investigator/investigator/cve_provided/__init__.py
  investigator/investigator/cve_provided/investigate_cve_provided.py
  investigator/investigator/cve_provided/metrics_cve_provided.py
  investigator/investigator/hash_mismatch/investigate_hash_mismatch.py
  investigator/investigator/missing_package/investigate_missing_package.py
  investigator/investigator/missing_version/investigate_missing_version.py
  investigator/investigator/solved_package/investigate_solved_package.py
Labels: approved, size/L

#364 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#365 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/L

#366 Automatic update of dependency hypothesis from 5.38.1 to 5.40.0
  Pipfile.lock
Labels: approved, bot, size/L
