Repository thoth-station/investigator, pull requests merged in 2020-11, with the labels that each got.

#369 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, size/M

#370 Automatic update of dependency thoth-sourcemanagement from 0.3.2 to 0.3.3
  Pipfile.lock
Labels: approved, bot, size/M

#371 Automatic update of dependency hypothesis from 5.40.0 to 5.41.0
  Pipfile.lock
Labels: approved, bot, size/M

#373 Automatic update of dependency thoth-storages from 0.25.16 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/M

#374 Automatic update of dependency hypothesis from 5.41.0 to 5.41.2
  Pipfile.lock
Labels: approved, bot, size/XS

#375 add **kwargs so all funcs can be called the same
  thoth/investigator/advise_justification/investigate_advise_justification.py
  thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/adviser_trigger/metrics_adviser_trigger.py
  thoth/investigator/cve_provided/investigate_cve_provided.py
  thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
  thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  thoth/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  thoth/investigator/missing_package/investigate_missing_package.py
  thoth/investigator/missing_version/investigate_missing_version.py
  thoth/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  thoth/investigator/package_released/investigate_package_released.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  thoth/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  thoth/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  thoth/investigator/solved_package/investigate_solved_package.py
  thoth/investigator/unresolved_package/investigate_unresolved_package.py
  thoth/investigator/unrevsolved_package/investigate_unrevsolved_package.py
  thoth/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
Labels: approved, size/M

#376 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/M

#377 Automatic update of dependency thoth-sourcemanagement from 0.3.3 to 0.4.0
  Pipfile.lock
Labels: approved, bot, size/M

#382 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#386 adjust aicoe-ci and update the packages
  .aicoe-ci.yaml
  Pipfile.lock
Labels: approved, size/L
