Repository thoth-station/investigator, pull requests merged in 2020-05, with the labels that each got.

#11 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S

#12 Automatic update of dependency thoth-common from 0.13.2 to 0.13.3
  Pipfile.lock
Labels: bot, size/XS

#14 Automatic update of dependency thoth-messaging from 0.3.4 to 0.3.6
  Pipfile.lock
Labels: bot, size/M

#15 Unresolved package handler producer
  .zuul.yaml
  Pipfile
  Pipfile.lock
  README.md
  app.py
  app.sh
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/unresolved-package-handler-job-template.yaml
  producer.py
  setup.py
  tests/adviser-04ab56d6.json
  tests/test_unresolved_package_handler.py
  thoth/unresolved_package_handler/unresolved_package_handler.py
Labels: approved, size/XXL

#16 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/M

#17 Automatic update of dependency hypothesis from 5.14.0 to 5.15.0
  Pipfile.lock
Labels: bot, size/M

#19 Automatic update of dependency hypothesis from 5.15.0 to 5.15.1
  Pipfile.lock
Labels: bot, size/S

#18 Create unsolved package handler workflow template for adviser workflow
  openshift/unresolved-package-handler-job-template.yaml
  workflows/templates/unresolved-package-handler-template.yaml
Labels: approved, size/M

#20 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/S

#22 Automatic update of dependency thoth-common from 0.13.4 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#23 Automatic update of dependency pytest-cov from 2.8.1 to 2.9.0
  Pipfile.lock
Labels: bot, size/S

#24 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#21 Unresolved package handler consumer
  Pipfile
  Pipfile.lock
  consumer.py
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/unresolved-package-handler-consumer-template.yaml
  producer.py
  tests/test_unresolved_package_handler.py
  thoth/unresolved_package_handler/__init__.py
  thoth/unresolved_package_handler/unresolved_package_handler.py
Labels: approved, size/L

#26 Automatic update of dependency hypothesis from 5.15.1 to 5.16.0
  Pipfile.lock
Labels: bot, size/S

#27 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M

#28 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/S
