Repository thoth-station/investigator, pull requests merged in 2021-06, with the labels that each got.

#529 expect only single index in message contents
  thoth/investigator/unresolved_package/investigate_unresolved_package.py
Labels: approved, size/S

#531 remove inner loop which loops over registered indexes
  thoth/investigator/unresolved_package/investigate_unresolved_package.py
Labels: approved, size/M

#538 set badges for easy access to content
  README.rst
Labels: approved, size/XS

#540 Deprecate qeb-hwt trigger message consumer
  README.rst
  consumer.py
  thoth/investigator/provenance_checker_trigger/metrics_provenance_checker_trigger.py
  thoth/investigator/qebhwt_trigger/README.md
  thoth/investigator/qebhwt_trigger/__init__.py
  thoth/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  thoth/investigator/qebhwt_trigger/metrics_qebhwt_trigger.py
Labels: approved, size/L

#534 mark missing packages and schedule keb admin
  thoth/investigator/missing_package/investigate_missing_package.py
Labels: approved, lgtm, size/M
