Repository thoth-station/investigator, pull requests merged in 2021-01, with the labels that each got.

#390 Remove use-before-declared linter warning
  thoth/investigator/common.py
Labels: approved, size/XS

#391 Do not use mutable arguments in functions
  thoth/investigator/common.py
Labels: approved, size/S

#405 Manual update of dependencies
  Pipfile.lock
Labels: approved, size/S

#393 Buildlog analysis trigger
  consumer.py
  thoth/investigator/build_analsysis_trigger/README.md
  thoth/investigator/build_analsysis_trigger/__init__.py
  thoth/investigator/build_analsysis_trigger/investigate_build_analysis_trigger.py
  thoth/investigator/build_analsysis_trigger/metrics_build_analysis_trigger.py
Labels: approved, size/L

#410 analsysis->analysis
  thoth/investigator/build_analysis_trigger/README.md
  thoth/investigator/build_analysis_trigger/__init__.py
  thoth/investigator/build_analysis_trigger/investigate_build_analysis_trigger.py
  thoth/investigator/build_analysis_trigger/metrics_build_analysis_trigger.py
Labels: approved, size/XS

#409 remove message contents (link instead)
  thoth/investigator/advise_justification/README.md
  thoth/investigator/adviser_re_run/README.md
  thoth/investigator/adviser_trigger/README.md
  thoth/investigator/build_analysis_trigger/README.md
  thoth/investigator/cve_provided/README.md
  thoth/investigator/hash_mismatch/README.md
  thoth/investigator/kebechet_run_url_trigger/README.md
  thoth/investigator/kebechet_trigger/README.md
  thoth/investigator/missing_package/README.md
  thoth/investigator/missing_version/README.md
  thoth/investigator/package_extract_trigger/README.md
  thoth/investigator/package_released/README.md
  thoth/investigator/provenance_checker_trigger/README.md
  thoth/investigator/qebhwt_trigger/README.md
  thoth/investigator/si_unanalyzed_package/README.md
  thoth/investigator/solved_package/README.md
  thoth/investigator/unresolved_package/README.md
  thoth/investigator/unrevsolved_package/README.md
  thoth/investigator/update_provide_source_distro/README.md
Labels: approved, size/L

#418 Update dependencies to have more recent thoth-common
  Pipfile.lock
Labels: approved, size/M

#417 Add "Kebechet update" and "Kebechet info" issue templates
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
Labels: approved, size/S

#424 decs are applied inside-out
  thoth/investigator/advise_justification/investigate_advise_justification.py
  thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/build_analysis_trigger/investigate_build_analysis_trigger.py
  thoth/investigator/cve_provided/investigate_cve_provided.py
  thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
  thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  thoth/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  thoth/investigator/missing_package/investigate_missing_package.py
  thoth/investigator/missing_version/investigate_missing_version.py
  thoth/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  thoth/investigator/package_released/investigate_package_released.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  thoth/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  thoth/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  thoth/investigator/solved_package/investigate_solved_package.py
  thoth/investigator/unresolved_package/investigate_unresolved_package.py
  thoth/investigator/unrevsolved_package/investigate_unrevsolved_package.py
  thoth/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
Labels: approved, size/M

#389 retry on exceptions and other error handling
  consumer.py
  thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
  thoth/investigator/common.py
  thoth/investigator/configuration.py
  thoth/investigator/metrics.py
Labels: approved, size/L

#428 Add metric schema
  consumer.py
  thoth/investigator/metrics.py
Labels: approved, size/S

#434 Standardize metrics for revision check
  consumer.py
  thoth/investigator/advise_justification/investigate_advise_justification.py
  thoth/investigator/configuration.py
  thoth/investigator/metrics.py
Labels: approved, size/S
