Repository thoth-station/investigator, pull requests merged in 2021-05, with the labels that each got.

#500 F/pydantic consumer
  Pipfile
  Pipfile.lock
  consumer.py
  thoth/investigator/advise_justification/investigate_advise_justification.py
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/build_analysis_trigger/investigate_build_analysis_trigger.py
  thoth/investigator/common.py
  thoth/investigator/cve_provided/investigate_cve_provided.py
  thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
  thoth/investigator/inspection_completed/investigate_inspection_completed.py
  thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  thoth/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  thoth/investigator/missing_package/investigate_missing_package.py
  thoth/investigator/missing_version/investigate_missing_version.py
  thoth/investigator/package_extract_trigger/investigate_package_extract_trigger.py
  thoth/investigator/package_released/investigate_package_released.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
  thoth/investigator/qebhwt_trigger/investigate_qebhwt_trigger.py
  thoth/investigator/si_unanalyzed_package/investigate_si_unanalyzed_package.py
  thoth/investigator/solved_package/investigate_solved_package.py
  thoth/investigator/unresolved_package/investigate_unresolved_package.py
  thoth/investigator/unrevsolved_package/investigate_unrevsolved_package.py
  thoth/investigator/update_provide_source_distro/investigate_update_provide_source_distro.py
Labels: approved, lgtm, size/L

#508 Relock the dependencies for fix sqlalchemy-utils
  Pipfile.lock
Labels: size/S

#515 messages are no longer classes
  consumer.py
Labels: approved, size/XS

#521 remove thoth-sourcemanagement from dependencies
  Pipfile
  Pipfile.lock
Labels: approved, lgtm, size/L
