Repository thoth-station/investigator, pull requests merged in 2021-04, with the labels that each got.

#480 use function as handler for all versions of message
  thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Labels: approved, lgtm, size/XS

#478 constrain thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/XS

#488 Changes for publishing on thoth-station.ninja
  README.rst
  setup.py
Labels: approved, size/M

#489 Constrain thoth-messaging to <=0.13
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#492 Adviser trigger message v4
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Labels: approved, size/XS

#495 Fix type for the authenticated parameter
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Labels: approved, size/XS

#498 Remove adviser re run message consumer
  README.rst
  consumer.py
  thoth/investigator/adviser_re_run/README.md
  thoth/investigator/adviser_re_run/__init__.py
  thoth/investigator/adviser_re_run/investigate_adviser_re_run.py
  thoth/investigator/adviser_re_run/metrics_adviser_re_run.py
Labels: approved, size/L
