Repository thoth-station/investigator, pull requests merged in 2021-07, with the labels that each got.

#556 add docs for envvar and endpoint
  README.rst
Labels: approved, size/S

#559 rename from 'paused' to 'halted'
  README.rst
  consumer.py
  thoth/investigator/metrics.py
Labels: approved, size/M

#563 remove unusued parameters
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/images/FailedAdviceAdviserReRun.png
Labels: approved, size/XS

#564 Adjust CI prow
  .pre-commit-config.yaml
  .prow.yaml
  setup.py
  thoth/investigator/cve_provided/investigate_cve_provided.py
  thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
  thoth/investigator/kebechet_trigger/investigate_kebechet_trigger.py
  thoth/investigator/metrics.py
  thoth/investigator/missing_package/investigate_missing_package.py
  thoth/investigator/missing_version/investigate_missing_version.py
  thoth/investigator/package_released/investigate_package_released.py
  thoth/investigator/solved_package/investigate_solved_package.py
Labels: approved, size/L
