Repository thoth-station/investigator, pull requests merged in 2021-03, with the labels that each got.

#465 if handler hasn't been registered treat it the same as messagea excep…
  consumer.py
  thoth/investigator/metrics.py
Labels: approved, size/M

#466 :arrow_up: update pre-commit plugins, CI related configs
  .aicoe-ci.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .prow.yaml
  OWNERS
Labels: approved, size/M

#467 F/message metrics
  consumer.py
  thoth/investigator/common.py
  thoth/investigator/configuration.py
  thoth/investigator/metrics.py
Labels: approved, size/L

#469 add new args to function call
  thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py
  thoth/investigator/package_extract_trigger/investigate_package_extract_trigger.py
Labels: approved, size/XS

#471 relock the dependencies
  Pipfile
  Pipfile.lock
Labels: size/L

#476 add new function args to call
  thoth/investigator/adviser_trigger/investigate_adviser_trigger.py
  thoth/investigator/provenance_checker_trigger/investigate_provenance_checker_trigger.py
Labels: approved, size/XS
